"""Build data/images.js from images/, then inline app.js, tooth.js and the data files into one HTML file:
dist/statistical-tooth.html. Run after build_data.py."""
import base64, json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
IMGDIR = os.path.join(HERE, "images")
MIME = {".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".webp": "image/webp"}
imgs = {}
if os.path.isdir(IMGDIR):
    for f in sorted(os.listdir(IMGDIR)):
        stem, ext = os.path.splitext(f)
        if ext.lower() not in MIME: continue
        key = stem[4:] if stem.startswith("era-") else stem
        with open(os.path.join(IMGDIR, f), "rb") as fh:
            imgs[key] = "data:" + MIME[ext.lower()] + ";base64," + base64.b64encode(fh.read()).decode()
with open(os.path.join(HERE, "data", "images.js"), "w") as fh:
    fh.write("// Generated by bundle.py from images/. Keys: " + ", ".join(imgs) + "\nwindow.ERA_IMAGES = " + json.dumps(imgs) + ";\n")
html = open(os.path.join(HERE, "index.html"), encoding="utf-8").read()
def inline(m):
    src = m.group(1)
    if src.startswith("http"): return m.group(0)
    js = open(os.path.join(HERE, src), encoding="utf-8").read().replace("</script", "<\\/script")
    return "<script>/* " + src + " */\n" + js + "\n</script>"
out = re.sub(r'<script src="([^"]+)"></script>', inline, html)
os.makedirs(os.path.join(HERE, "dist"), exist_ok=True)
p = os.path.join(HERE, "dist", "statistical-tooth.html")
open(p, "w", encoding="utf-8").write(out)
print(p, round(len(out.encode()) / 1024), "KB; images:", ", ".join(imgs) or "none")
